name: moliya_studyasi
description: "A new Flutter project."

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.6
  firebase_core: ^2.30.0
  flutter_screenutil: ^5.9.0
  intl: ^0.19.0
  qr_code_scanner: ^1.0.1
  cloud_firestore: ^4.17.2
  firebase_auth: ^4.19.4
  flutter_bloc: ^8.1.5
  bloc: ^8.1.4
  shared_preferences: ^2.2.3
  equatable: ^2.0.5
  geocoding: ^3.0.0
  location: ^6.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.0


flutter:


  uses-material-design: true

  assets:
    - assets/images/



  fonts:
     - family: Lato
       fonts:
         - asset: assets/fonts/Lato-Regular.ttf
         - asset: assets/fonts/Lato-Bold.ttf
           weight: 700

